In [1]:
# ============================================================
# STEAM 200K DATASET
# NLP + TF-IDF + K-MEANS CLUSTERING
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import string
import warnings

warnings.filterwarnings("ignore")

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import TruncatedSVD

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

print("All libraries imported successfully.")

All libraries imported successfully.

In [2]:
# ============================================================
# DOWNLOAD NLTK RESOURCES
# ============================================================

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("NLTK resources ready.")

NLTK resources ready.

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [3]:
# ============================================================
# LOAD DATASET
# ============================================================

FILE_PATH = "steam-200k.csv"

df = pd.read_csv(
    FILE_PATH,
    header=None
)

print("Dataset loaded.")
print("Shape:", df.shape)

display(df.head())

Dataset loaded.
Shape: (200000, 5)

           0                           1         2      3  4
0  151603712  The Elder Scrolls V Skyrim  purchase    1.0  0
1  151603712  The Elder Scrolls V Skyrim      play  273.0  0
2  151603712                   Fallout 4  purchase    1.0  0
3  151603712                   Fallout 4      play   87.0  0
4  151603712                       Spore  purchase    1.0  0

In [4]:
# ============================================================
# DETECT DATASET FORMAT
# ============================================================

print("Number of columns:", len(df.columns))

print("\nFirst rows:")
display(df.head(10))

Number of columns: 5

First rows:

           0                           1         2      3  4
0  151603712  The Elder Scrolls V Skyrim  purchase    1.0  0
1  151603712  The Elder Scrolls V Skyrim      play  273.0  0
2  151603712                   Fallout 4  purchase    1.0  0
3  151603712                   Fallout 4      play   87.0  0
4  151603712                       Spore  purchase    1.0  0
5  151603712                       Spore      play   14.9  0
6  151603712           Fallout New Vegas  purchase    1.0  0
7  151603712           Fallout New Vegas      play   12.1  0
8  151603712               Left 4 Dead 2  purchase    1.0  0
9  151603712               Left 4 Dead 2      play    8.9  0

In [5]:
# ============================================================
# ASSIGN COLUMN NAMES
# ============================================================

if len(df.columns) == 5:

    df.columns = [
        "user_id",
        "game",
        "behavior",
        "value",
        "extra"
    ]

elif len(df.columns) == 4:

    df.columns = [
        "user_id",
        "game",
        "behavior",
        "value"
    ]

else:

    # Generic names for unexpected formats
    df.columns = [
        f"column_{i}"
        for i in range(len(df.columns))
    ]

print("Column names:")
print(df.columns.tolist())

display(df.head())

Column names:
['user_id', 'game', 'behavior', 'value', 'extra']

     user_id                        game  behavior  value  extra
0  151603712  The Elder Scrolls V Skyrim  purchase    1.0      0
1  151603712  The Elder Scrolls V Skyrim      play  273.0      0
2  151603712                   Fallout 4  purchase    1.0      0
3  151603712                   Fallout 4      play   87.0      0
4  151603712                       Spore  purchase    1.0      0

In [6]:
# ============================================================
# DATASET INFORMATION
# ============================================================

print("Dataset shape:")
print(df.shape)

print("\nColumn information:")
print(df.info())

print("\nMissing values:")
display(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Dataset shape:
(200000, 5)

Column information:
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   user_id   200000 non-null  int64
 1   game      200000 non-null  str
 2   behavior  200000 non-null  str
 3   value     200000 non-null  float64
 4   extra     200000 non-null  int64
dtypes: float64(1), int64(2), str(2)
memory usage: 12.4 MB
None

Missing values:

user_id     0
game        0
behavior    0
value       0
extra       0
dtype: int64

Duplicate rows:
707

In [7]:
# ============================================================
# BASIC DATA CLEANING
# ============================================================

# Remove completely empty rows
df = df.dropna(how="all")

# Remove rows without a game name
df["game"] = df["game"].fillna("").astype(str)

df = df[
    df["game"].str.strip() != ""
]

# Remove duplicate rows
df = df.drop_duplicates()

# Reset index
df = df.reset_index(drop=True)

print("Cleaned dataset shape:", df.shape)

display(df.head())

Cleaned dataset shape: (199293, 5)

     user_id                        game  behavior  value  extra
0  151603712  The Elder Scrolls V Skyrim  purchase    1.0      0
1  151603712  The Elder Scrolls V Skyrim      play  273.0      0
2  151603712                   Fallout 4  purchase    1.0      0
3  151603712                   Fallout 4      play   87.0      0
4  151603712                       Spore  purchase    1.0      0